spring:
  profiles:
    active: local

---

spring:
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/batch-demo
      username: jwlee
      password: jwlee
      driver-class-name: com.mysql.jdbc.Driver
  config:
    activate:
      on-profile: local